/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.AdminRole;
import java.io.IOException;


/**
 *
 * @author youssef
 */
public class AdminRoleWindow extends javax.swing.JFrame {
static AdminRole admin;
static {
    try {
        admin = new AdminRole(Constants.FileNames.TRAINER_FILENAME);
    } catch (IOException e) {
    }
}
    /**
     * Creates new form AdminRole
     */
    public AdminRoleWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddTrainer = new javax.swing.JButton();
        btnDisplayTrainers = new javax.swing.JButton();
        btnRemoveTrainers = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/icons/businessman.png"))); // NOI18N
        jLabel1.setText("ADMIN ROLE");

        btnAddTrainer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddTrainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/icons/add.png"))); // NOI18N
        btnAddTrainer.setText("ADD TRAINER");
        btnAddTrainer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainerActionPerformed(evt);
            }
        });

        btnDisplayTrainers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDisplayTrainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/icons/monitor.png"))); // NOI18N
        btnDisplayTrainers.setText("DISPLAY TRAINERS");
        btnDisplayTrainers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDisplayTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayTrainersActionPerformed(evt);
            }
        });

        btnRemoveTrainers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveTrainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/icons/remove.png"))); // NOI18N
        btnRemoveTrainers.setText("REMOVE TRAINER");
        btnRemoveTrainers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemoveTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTrainersActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/icons/logout.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAddTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnDisplayTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRemoveTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainerActionPerformed
        //opens new AddTrainerWindow and disposes of this window
        new AddTrainerWindow().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnAddTrainerActionPerformed

    private void btnDisplayTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayTrainersActionPerformed
        //opens new DisplayTrainersWindow and disposes of this window
        new DisplayTrainersWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDisplayTrainersActionPerformed

    private void btnRemoveTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTrainersActionPerformed
        //opens new trainerrolewindow and disposes of this window
        new RemoveTrainerWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRemoveTrainersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        //save files and dispose of the window
        admin.logout();
        new MainFrame().setVisible(true);
        dispose();   
        
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminRoleWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrainer;
    private javax.swing.JButton btnDisplayTrainers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveTrainers;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
